title:               Sangkyu Son
url:                 https://sangkyuson.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Sangkyu Son
  url:               sangkyuson.github.io
  email:             ss.sangkyu.son@gmail.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
    
analytics:
  provider: "google"
  google:
    tracking_id: "G-6RRZLZRQTE"
    anonymize_ip: false # default
